spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/warehouse_prod
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Deactivate SQL logging in prod
spring.jpa.show-sql=false

# Disable automatic data seeding in prod
spring.sql.init.mode=never