### Fetch all tasks
GET  http://localhost:8080/api/v1/tasks/search
Content-Type: application/json

### Find Solution
POST http://localhost:8080/api/v1/dispatcher/solve
Content-Type: application/json

### Get solution
GET http://localhost:8080/api/v1/dispatcher/solve
Content-Type: application/json